### ISSUE TITLE
Link avatar are wrong

### ISSUE THREAD

**Issue by phanthinh** [ncoders/redmine_local_avatars#10]
Hi

I saw link http://localhost:3000/account/get_avatar/6

It's should be http://insight.zcoder.io/account/get_avatar/6

Can you help me please

**Comment by dup2** [comment]
The plugin uses `url_for` to generate a link and does not set any host/port options. However, an absolute path is generated.

Do other links in your installation point to localhost:3000 as well? Are you using a reverse proxy or access the installation directly? What is your setting "Hostname and path" in the Settings -> General tab for this installation?

**Comment by dup2** [comment]
I think this is fixed with MR #9.

Feel free to reopen if it does not work.
