### ISSUE TITLE
Redmine 3.1.0, NameError: uninitialized constant LocalAvatarsPlugin::UsersControllerPatch

### ISSUE THREAD

**Issue by ssrakesh** [ncoders/redmine_local_avatars#12]
Copied plugin in to redmine\htdocs\plugins\redmine_local_avatars
executed `bundle exec rake redmine:plugins:migrate RAILS_ENV="production"`
Error:
`rake aborted!
NameError: uninitialized constant LocalAvatarsPlugin::UsersControllerPatch
D:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/plugins/redmine_local_avatars/init.rb:37:in `block in <top (required)>'
D:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
D:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/plugins/a_common_libs/lib/tasks/a_common_libs.rake:1:in `<top (required)>'
D:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/lib/tasks/redmine.rake:179:in `block in <top (required)>'
D:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/lib/tasks/redmine.rake:179:in `each'
D:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/lib/tasks/redmine.rake:179:in `<top (required)>'
D:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/Rakefile:7:in `<top (required)>'
(See full trace by running task with --trace)`

**Comment by dup2** [comment]
This seems to happen when adding methods to existing controllers. This statement is called after successfully adding methods to the AccountController and others which work fine.

Does the file "users_controller_patch.rb" exist in "plugins/redmine_local_avatars/lib/" ?

**Comment by ssrakesh** [comment]
yes,  file "users_controller_patch.rb" exist in "plugins/redmine_local_avatars/lib/" .

**Comment by ssrakesh** [comment]
Hi, if you have any suggestions to try with the code base, let me know.
I don't have any experience in ruby, can definitely trying your suggestions in my test environment

**Comment by ssrakesh** [comment]
Reinstalled bitnami redmine and copied only local avatar, no Errors !

**Comment by dup2** [comment]
I see - the mega_calendar plugin also provides a `UsersControllerPatch` class which is unfortunately not namespaced and seems to clash with the one in this plugin at `LocalAvatarsPlugin::UsersControllerPatch`.

I'll close this one and add a note for the incompatibility.
