### ISSUE TITLE
Error 500. Wrong number of arguments (0 for 1..2) 

### ISSUE THREAD

**Issue by Chenzana** [ncoders/redmine_local_avatars#13]
Hello,
It works fine if I use (as admin)
Logged in as <my_login> => Edit => Avatar.

When I push
My account => Change local avatar
error is occurred.

Log is attached.
[redmineError.txt](https://github.com/ncoders/redmine_local_avatars/files/446932/redmineError.txt)

Environment:
  Redmine version               3.1.0.devel.14494
  Ruby version                     2.0.0-p384 (2014-01-12) [x86_64-linux-gnu]
  Rails version                      4.2.3
  Environment                     production
  Database adapter              Mysql2

**Comment by diversys** [comment]
Same here!

**Comment by mmohme** [comment]
And same here with Redmine 3.3.2.

**Comment by jolin7616** [comment]
And same here with Redmine 3.1.3.

**Comment by dup2** [comment]
Sorry, can not support an old version of Redmine anymore
