### ISSUE TITLE
Edit users (internal error)

### ISSUE THREAD

**Issue by 4ev** [ncoders/redmine_local_avatars#14]
redmine 3.3.0
redmine_local_avatars 1.0.3

ERROR 500
Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

Back

Log:

Started GET "/users/11/edit" for 10.1.8.220 at 2016-09-01 15:52:20 +0500
Processing by UsersController#edit as HTML
  Parameters: {"id"=>"11"}
  Current user: admin (id=1)
  Rendered plugins/a_common_libs/app/views/hooks/a_common_libs/_favourite_project.html.erb (16.8ms)
  Rendered plugins/redmine_intouch/app/views/settings/_telegram_user.html.erb (2.2ms)
  Rendered plugins/redmine_pretend/app/views/user/_pretend_to.html.erb (525.0ms)
  Rendered users/_form.html.erb (552.4ms)
  Rendered users/_general.html.erb (553.2ms)
  Rendered common/_tabs.html.erb (555.1ms)
  Rendered users/edit.html.erb within layouts/admin (560.8ms)
Completed 500 Internal Server Error in 573ms (ActiveRecord: 9.5ms)

ActionView::Template::Error (undefined method `can_user_pretend_to?' for #<#<Class:0x00000007c34950>:0x007fd6869995f8>):
    1: <%= link_to(l(:button_pretend), pretend_to_path(@user), :class => 'icon', :method => :post) if can_user_pretend_to?(@user)  %>
  plugins/redmine_pretend/app/views/user/_pretend_to.html.erb:1:in `_plugins_redmine_pretend_app_views_user__pretend_to_html_erb___2530822528522774163_26733360'
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in `map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/users/_form.html.erb:24:in `_app_views_users__form_html_erb__4322404218939536333_34811780'
  app/views/users/_general.html.erb:2:in `block in _app_views_users__general_html_erb__662679684733538143_35283340'
  app/helpers/application_helper.rb:1051:in `labelled_form_for'
  app/views/users/_general.html.erb:1:in `_app_views_users__general_html_erb__662679684733538143_35283340'
  app/views/common/_tabs.html.erb:17:in `block in _app_views_common__tabs_html_erb___2045936875574142465_35813400'
  app/views/common/_tabs.html.erb:16:in `each'
  app/views/common/_tabs.html.erb:16:in `_app_views_common__tabs_html_erb___2045936875574142465_35813400'
  app/helpers/application_helper.rb:325:in `render_tabs'
  app/views/users/edit.html.erb:10:in `_app_views_users_edit_html_erb___3716145409059403338_36717300'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by dup2** [comment]
The first log entry states the error is in plugins/redmine_pretend/app/views/user/_pretend_to.html.erb.

This is the plugin "redmine_pretend" and is not related to the local avatars. Please open an issue there.
