### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by axeloz** [ncoders/redmine_local_avatars#15]
I get a 404 error when trying to edit my own account. The error is:

`Rendered users/edit.html.erb within layouts/admin (233.4ms)
Missing template, responding with 404`

Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.0.0-p648 (2015-12-16) [x86_64-linux-gnu]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2

**Comment by dup2** [comment]
Sorry, can not support an old version of Redmine anymore
