### ISSUE TITLE
Unable to install plugin 

### ISSUE THREAD

**Issue by smoolya17** [ncoders/redmine_local_avatars#19]
I have redmine 3.3.3 installed in my server and I downloaded the latest source code of redmine_local_avatars into my plugins folder. Even after running the migration script. when server is restarted, I am unable to view it in the installed list of plugins.

What may be the issue? I have tested my redmine for other plugins. Is this problem due to those plugins?

**Comment by dup2** [comment]
Sorry, can not support an old version of Redmine anymore
