### ISSUE TITLE
error rake redmine:plugins:migrate RAILS_ENV=production

### ISSUE THREAD

**Issue by maximzar** [ncoders/redmine_local_avatars#27]
NameError: undefined method `avatar' for module `ApplicationHelper'

version redmine 4.1.1

![image](https://user-images.githubusercontent.com/78652928/114976168-349a3c80-9e8e-11eb-89e9-1cbc9f654a7a.png)

**Comment by saraf** [comment]
I just confirmed that this error is fixed if you use this fork of the plugin - https://github.com/taqueci/redmine_local_avatars

**Comment by dup2** [comment]
Fixed with 1.0.6
