### ISSUE TITLE
Update for 5.x

### ISSUE THREAD

**Issue by formigadiablo** [ncoders/redmine_local_avatars#32]
Is there any update for redmine 5.x? Or it exists an approximate date for its realization?

**Comment by rdemendoza** [comment]
+1

**Comment by minhtang1** [comment]
+1

**Comment by pengrun** [comment]
+1

**Comment by onlyjob** [comment]
The following patch seems to work: https://salsa.debian.org/debian/redmine-plugin-local-avatars/-/blob/master/debian/patches/r5.patch

**Comment by dup2** [comment]
Should be fixed with #33
