### ISSUE TITLE
Please add copyright statement and tag/release.

### ISSUE THREAD

**Issue by onlyjob** [ncoders/redmine_local_avatars#4]
Thanks for improving this excellent plugin.
Could you please add your copyright statement and tag a release?

**Comment by dup2** [comment]
Version 1.1.0 released.

**Comment by onlyjob** [comment]
Thanks. There is one minor problem left -- incorrect copyright statement

`2010-2015 Andrew Chaika, Luca Pireddu, dup2`.

Please do not modify original years of copyright because one can not extend someone else’s copyright.
It should be something like the following:

~~~~
Copyright 2010 Andrew Chaika, Luca Pireddu
Copyright 2015 dup2
~~~~

So your copyright is on the separate line next to original copyright statement.
Ideally instead of "dup2" there should be your name followed by email address.

---

FYI: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=790723
