### ISSUE TITLE
Create issue by email (redmine 3.0.x)

### ISSUE THREAD

**Issue by jack520810044** [ncoders/redmine_local_avatars#5]
Hi

I need to create issue by email.

So I run command line as a below .
rake -f /opt/redmine-3.0.2-0/apps/redmine/htdocs/Rakefile redmine:email:receive_imap RAILS_ENV="production" host=imap.gmail.com username=xxxxxxx@gmail.com password="xxxxxxx"

But I got error message ,as a below
 =====================================
rake aborted!
LoadError: cannot load such file -- application
/opt/redmine-3.0.2-0/apps/redmine/htdocs/plugins/redmine_local_avatars/lib/users_avatar_patch.rb:1:in `<top (required)>'
/opt/redmine-3.0.2-0/apps/redmine/htdocs/plugins/redmine_local_avatars/init.rb:3:in `<top (required)>'
/opt/redmine-3.0.2-0/apps/redmine/htdocs/lib/redmine/plugin.rb:155:in `block in load'
/opt/redmine-3.0.2-0/apps/redmine/htdocs/lib/redmine/plugin.rb:146:in `each'
/opt/redmine-3.0.2-0/apps/redmine/htdocs/lib/redmine/plugin.rb:146:in `load'
/opt/redmine-3.0.2-0/apps/redmine/htdocs/config/initializers/30-redmine.rb:21:in `<top (required)>'
/opt/redmine-3.0.2-0/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
Tasks: TOP => redmine:email:receive_imap => environment
(See full trace by running task with --trace)

Please help me.

**Comment by dup2** [comment]
This plugin is only tested with the redmine versions 2.1 - 2.6, see the file README.md for compatibility information.

You are using redmine 3.0.2 - sorry, I can't help you with this as I do not run it on a 3.x version here. Pull requests welcome :smiley:
