### ISSUE TITLE
Support for redmine 3.x?

### ISSUE THREAD

**Issue by ilovetacos** [ncoders/redmine_local_avatars#8]
Hi,
are you planning to release a version for redmine 3.x?
Thank you very much!

**Comment by prohde** [comment]
Did you have issues with Redmine 3.x? I recently upgraded my Redmine instance to 3.1.1 and didn't experienced any issues up to this moment.

**Comment by ilovetacos** [comment]
I haven't tried yet. I'm trying to find out about compatibilities before I upgrade. Thank you for the information, tho :)

**Comment by dup2** [comment]
There is no plan for a 3.x compatibility right now - I'm happy to hear that it works.

**Comment by erema15** [comment]
It works on 3.2

**Comment by dup2** [comment]
Thanks for the information :ok_hand:
